# Generated by Django 3.2.18 on 2023-05-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboar', '0002_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
